name: SonarCloud Code Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - uses: actions/checkout@v2

      # Set up Node.js 18
      - name: Set up Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Install dependencies with npm (optional if applicable)
      - name: Install dependencies
        run: npm install

      # Set up JDK 11 for Maven build
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      # Build with Maven
      - name: Build with Maven
        run: mvn clean install

      # Run SonarCloud scan
      - name: Run SonarCloud scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_PROJECT_KEY: ${{ vars.SONAR_PROJECT_KEY }}
          SONAR_ORGANIZATION: ${{ vars.SONAR_ORGANIZATION }}
        run: mvn sonar:sonar \
          -Dsonar.projectKey=${{ vars.SONAR_PROJECT_KEY }} \
          -Dsonar.organization=${{ vars.SONAR_ORGANIZATION }} \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
